.PHONY: clean All

All:
	@echo "----------Building project:[ ArraysExample - Debug ]----------"
	@cd "ArraysExample" && "$(MAKE)" -f  "ArraysExample.mk"
clean:
	@echo "----------Cleaning project:[ ArraysExample - Debug ]----------"
	@cd "ArraysExample" && "$(MAKE)" -f  "ArraysExample.mk" clean
