.PHONY: clean All

All:
	@echo "----------Building project:[ Arraysmoreexamples - Debug ]----------"
	@cd "Arraysmoreexamples" && "$(MAKE)" -f  "Arraysmoreexamples.mk"
clean:
	@echo "----------Cleaning project:[ Arraysmoreexamples - Debug ]----------"
	@cd "Arraysmoreexamples" && "$(MAKE)" -f  "Arraysmoreexamples.mk" clean
