.PHONY: clean All

All:
	@echo "----------Building project:[ Comments - Debug ]----------"
	@cd "Comments" && "$(MAKE)" -f  "Comments.mk"
clean:
	@echo "----------Cleaning project:[ Comments - Debug ]----------"
	@cd "Comments" && "$(MAKE)" -f  "Comments.mk" clean
