.PHONY: clean All

All:
	@echo "----------Building project:[ EurostoUSD - Debug ]----------"
	@cd "EurostoUSD" && "$(MAKE)" -f  "EurostoUSD.mk"
clean:
	@echo "----------Cleaning project:[ EurostoUSD - Debug ]----------"
	@cd "EurostoUSD" && "$(MAKE)" -f  "EurostoUSD.mk" clean
